/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMessage: typeof import('./resources/js/Components/ActionMessage.vue')['default']
    ActionSection: typeof import('./resources/js/Components/ActionSection.vue')['default']
    Alert: typeof import('./resources/js/Components/Widgets/Alert.vue')['default']
    AppLayout: typeof import('./resources/js/Layouts/AppLayout.vue')['default']
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    ApplicationMark: typeof import('./resources/js/Components/ApplicationMark.vue')['default']
    AuthButton: typeof import('./resources/js/Components/Auth/AuthButton.vue')['default']
    AuthCard: typeof import('./resources/js/Components/Auth/AuthCard.vue')['default']
    AuthenticationCard: typeof import('./resources/js/Components/AuthenticationCard.vue')['default']
    AuthenticationCardLogo: typeof import('./resources/js/Components/AuthenticationCardLogo.vue')['default']
    AuthInput: typeof import('./resources/js/Components/Auth/AuthInput.vue')['default']
    Banner: typeof import('./resources/js/Components/Banner.vue')['default']
    BaseSelect: typeof import('./resources/js/Components/Widgets/BaseSelect.vue')['default']
    Button: typeof import('./resources/js/Components/Widgets/Button.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    ConfirmationModal: typeof import('./resources/js/Components/ConfirmationModal.vue')['default']
    ConfirmsPassword: typeof import('./resources/js/Components/ConfirmsPassword.vue')['default']
    Container: typeof import('./resources/js/Components/Widgets/Container.vue')['default']
    CreateCustomerButton: typeof import('./resources/js/Components/Forms/CreateCustomerButton.vue')['default']
    CreateCustomerForm: typeof import('./resources/js/Components/Forms/CreateCustomerForm.vue')['default']
    CreateMerchantButon: typeof import('./resources/js/Components/Forms/CreateMerchantButton.vue')['default']
    CreateMerchantButton: typeof import('./resources/js/Components/Forms/CreateMerchantButton.vue')['default']
    CreateMerchantForm: typeof import('./resources/js/Components/Forms/CreateMerchantForm.vue')['default']
    CreateTransactionButton: typeof import('./resources/js/Components/Forms/CreateTransactionButton.vue')['default']
    CreateTransactionForm: typeof import('./resources/js/Components/Forms/CreateTransactionForm.vue')['default']
    CreateTransationButton: typeof import('./resources/js/Components/Forms/CreateTransationButton.vue')['default']
    CreateTransationForm: typeof import('./resources/js/Components/Forms/CreateTransationForm.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    DataTable: typeof import('./resources/js/Components/Widgets/DataTable.vue')['default']
    Dialog: typeof import('./resources/js/Components/Widgets/Dialog.vue')['default']
    DialogModal: typeof import('./resources/js/Components/DialogModal.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    FormSection: typeof import('./resources/js/Components/FormSection.vue')['default']
    Hours: typeof import('./resources/js/Components/Widgets/Hours.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/Components/Auth/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    Pagination: typeof import('./resources/js/Components/Widgets/Pagination.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    SectionBorder: typeof import('./resources/js/Components/SectionBorder.vue')['default']
    SectionTitle: typeof import('./resources/js/Components/SectionTitle.vue')['default']
    SelectInput: typeof import('./resources/js/Components/Widgets/SelectInput.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
    Welcome: typeof import('./resources/js/Components/Welcome.vue')['default']
  }
}
